#pragma once
#include <flecs.h>
#include "mg_comp.h"
ECS_TAG_DECLARE (tag_gl_programlinked);
ECS_COMPONENT_DECLARE (component_gl_program);
ECS_COMPONENT_DECLARE (component_gl_shader);
ECS_COMPONENT_DECLARE (component_gl_tex2darray);
ECS_COMPONENT_DECLARE (component_vbo);
ECS_COMPONENT_DECLARE (component_vao);
ECS_COMPONENT_DECLARE (component_va);
ECS_COMPONENT_DECLARE (component_lines);
ECS_COMPONENT_DECLARE (component_texture);
ECS_COMPONENT_DECLARE (component_pointcloud);
ECS_COMPONENT_DECLARE (component_mesh);
ECS_COMPONENT_DECLARE (component_stride);
ECS_COMPONENT_DECLARE (component_count);
ECS_COMPONENT_DECLARE (component_color);
ECS_COMPONENT_DECLARE (component_position);
ECS_COMPONENT_DECLARE (component_scale);
ECS_COMPONENT_DECLARE (component_quaternion);
ECS_COMPONENT_DECLARE (component_uv);
ECS_COMPONENT_DECLARE (component_rectangle);
ECS_COMPONENT_DECLARE (component_transform);
ECS_COMPONENT_DECLARE (component_filename);
ECS_COMPONENT_DECLARE (component_controller);
ECS_COMPONENT_DECLARE (component_applyrotation);
