#pragma once
#include <flecs.h>
#include "mg_comp.h"
ECS_TAG_DECLARE (ProgramLinked_OpenGL);
ECS_COMPONENT_DECLARE (Program_OpenGL);
ECS_COMPONENT_DECLARE (Shader_OpenGL);
ECS_COMPONENT_DECLARE (Tex2DArray_OpenGL);
ECS_COMPONENT_DECLARE (VBO_OpenGL);
ECS_COMPONENT_DECLARE (VAO_OpenGL);
ECS_COMPONENT_DECLARE (VA_OpenGL);

ECS_COMPONENT_DECLARE (Lines_OpenGL);
ECS_COMPONENT_DECLARE (Texture_OpenGL);
ECS_COMPONENT_DECLARE (Pointcloud_OpenGL);
ECS_COMPONENT_DECLARE (Mesh_OpenGL);

ECS_COMPONENT_DECLARE (Stride);
ECS_COMPONENT_DECLARE (Capacity);
ECS_COMPONENT_DECLARE (Count);
ECS_COMPONENT_DECLARE (Offset);

ECS_COMPONENT_DECLARE (Color);
ECS_COMPONENT_DECLARE (Position4);
ECS_COMPONENT_DECLARE (Scale4);
ECS_COMPONENT_DECLARE (Quaternion);
ECS_COMPONENT_DECLARE (TextureUV);
ECS_COMPONENT_DECLARE (Rectangle2f);
ECS_COMPONENT_DECLARE (Transform);
ECS_COMPONENT_DECLARE (Filename);
ECS_COMPONENT_DECLARE (Keyboard_SDL);
ECS_COMPONENT_DECLARE (QuaternionDelta);
